name: CI/CD to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE_NAME: farmatodo
      IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/farmatodo-repo/farmatodo:latest
      API_KEY_BASE64: ${{ secrets.API_KEY_BASE64 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate gcloud & Docker
        run: |
          echo "$GCP_SA_KEY" > ./google-credentials.json
          gcloud auth login --brief --cred-file=./google-credentials.json --update-adc
          gcloud auth configure-docker --quiet

      - name: Build Maven project
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          echo "Building Docker image: $IMAGE"
          docker build -t "$IMAGE" .

      - name: Push Docker image to Artifact Registry
        run: |
          echo "Pushing Docker image: $IMAGE"
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image "$IMAGE" \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars API_KEY_BASE64="$API_KEY_BASE64"
