name: CI/CD to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}            # Ej: us-central1
      SERVICE_NAME: farmatodo
      IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/farmatodo-repo/farmatodo:latest
      API_KEY_BASE64: ${{ secrets.API_KEY_BASE64 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project $PROJECT_ID

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build Maven project
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Verify Docker image
        run: docker images | grep farmatodo

      - name: Push Docker image to Artifact Registry
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars API_KEY_BASE64=$API_KEY_BASE64
